### ISSUE TITLE
Add date picker

### ISSUE THREAD

**Issue by denishrana09** [yogeshkrishnani/vaccine-notifier#2]
government opens 3 days slots at once,
so if we can select date then this will be more useful!

**Comment by yogeshkrishnani** [comment]
@denishrana09 

The current api returns all the slots of next 5 days w.r.t date we've passed.

So I don't think we need to add date picker or date range picker.

Let me know if you think otherwise.

**Comment by denishrana09** [comment]
Actually what I have saw is, notifier is sending tomorrow's date in API,
Can you help me, how you are able to see next 5 days slots!

**Comment by yogeshkrishnani** [comment]
@denishrana09 

Yes, you're right, the application will send tomorrow's date, if you're checking the slot after 5 PM.

But, that api returns the availability of slots for next 7 days, earlier it was 5 days. 

Go to https://apisetu.gov.in/public/marketplace/api/cowin/cowinapi-v2#/Vaccination%20Appointment%20APIs/calendarByDistrict and search calendarByDistrict.
